name: Backend CI

on:
  push:
    paths:
      - 'back-end/**'
  pull_request:
    paths:
      - 'back-end/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: |
          cd back-end
          mvn clean install

  snyk:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk
        uses: snyk/actions/setup@master
        with:
          version: 'latest'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to check for vulnerabilities
        run: |
          cd back-end
          snyk monitor --org=my-org
          snyk test --severity-threshold=medium