name: Backend CI

on:
  push:
    paths:
      - 'back-end/**'
  pull_request:
    paths:
      - 'back-end/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: |
          cd back-end
          mvn clean install


  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Run Maven tests
        run: |
          cd back-end
          mvn test

  snyk:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Run Snyk to check for vulnerabilities
        run: |
          cd back-end
          snyk test --severity-threshold=high || true

  deploy:
    needs: snyk
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # 仅在 main 分支上执行部署

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y sshpass

      - name: Login to Docker Hub and Build and Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/questify-backend ./back-end  # 替换为实际的 Docker Hub 用户名和镜像名
          docker push ${{ secrets.DOCKER_USERNAME }}/questify-backend # 替换为实际的 Docker Hub 用户名和镜像名

      - name: Deploy to Remote Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          # 将私钥添加到 SSH agent
          echo "$SSH_PRIVATE_KEY" > id_rsa
          chmod 600 id_rsa
          
          # 使用 scp 将 docker-compose.yml Dockerfile复制到远程服务器
          scp -i id_rsa -o StrictHostKeyChecking=no docker-compose.yml $SSH_USERNAME@$SSH_HOST:/home/SE5006/questify/
          scp -i id_rsa -o StrictHostKeyChecking=no ./back-end/Dockerfile $SSH_USERNAME@$SSH_HOST:/home/SE5006/questify/back-end/
          scp -i id_rsa -o StrictHostKeyChecking=no ./front-end/Dockerfile $SSH_USERNAME@$SSH_HOST:/home/SE5006/questify/front-end/

          # SSH 连接并在远程服务器上执行命令
          ssh -i id_rsa -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST << 'EOF'

          # 进入到部署的工作目录
          cd /home/SE5006/questify  # 使用服务器上项目的实际路径
          
          # 拉取前端镜像
          docker pull ${{ secrets.DOCKER_USERNAME }}/questify-frontend
          
          # 拉取后端镜像
          docker pull ${{ secrets.DOCKER_USERNAME }}/questify-backend
          
          # 停止旧的容器
          docker-compose down

          # 使用 docker-compose 构建和启动新容器
          docker-compose up -d --build
          EOF