name: Backend CI

on:
  push:
    paths:
      - 'back-end/**'
  pull_request:
    paths:
      - 'back-end/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: |
          cd back-end
          mvn clean install


  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Run Maven tests
        run: |
          cd back-end
          mvn test

  snyk:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Run Snyk to check for vulnerabilities
        run: |
          cd back-end
          snyk test --severity-threshold=high || true

  release:
    needs: snyk
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only runs on the main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git for tag creation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get current version from pom.xml
        id: version
        run: |
          # 获取当前版本号
          CURRENT_VERSION=$(cat back-end/pom.xml | grep -m1 -oPm1 '(?<=<version>)[^<]+')

          # 递增版本号（这里递增 patch，你可以改为 minor 或 major）
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$3+=1; print}')

          # 更新 pom.xml 中的版本号
          sed -i "s|<version>$CURRENT_VERSION</version>|<version>$NEW_VERSION</version>|" back-end/pom.xml

          # 将新版本号写入环境变量
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit updated version
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add back-end/pom.xml
          git commit -m "Bump backend version to $NEW_VERSION"
          git push origin main  # 提交新版本号

      - name: Create and push tag with prefix
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          # 使用前缀创建带版本的标签
          TAG_NAME="backend-v$VERSION"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "Release v${{ env.VERSION }}"
          body: |
            Automated release for version v${{ env.VERSION }}
          draft: false
          prerelease: false

  deploy:
    needs: release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # 仅在 main 分支上执行部署

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y sshpass

      - name: Login to Docker Hub and Build and Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/questify-backend ./back-end  # 替换为实际的 Docker Hub 用户名和镜像名

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/questify-backend # 替换为实际的 Docker Hub 用户名和镜像名

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ${{ secrets.SSH_HOST }}, -u ${{ secrets.SSH_USERNAME }} ./.github/workflows/deploy.yml --extra-vars "docker_username=${{ secrets.DOCKER_USERNAME }} target_host=${{ secrets.SSH_HOST }}"