name: Frontend CI

on:
  push:
    paths:
      - 'front-end/**'
  pull_request:
    paths:
      - 'front-end/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # 或其他版本

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build application
        run: |
          cd front-end
          npm run build